const labs = [
  {
    id: 1,
    name: "Laboratoire D'analyse Médical Dr Gherib",
    phone: "0696100200",
    adress: "وراء محكمة الوئام مقابل مسجد عبدالله بن عمر",
    workTime: "7:30-14:30",
  },
  {
    id: 2,
    name: "Laboratoire D'analyse Médical Dr Khenfar ImadEddien",
    phone: "0666736570",
    adress: "حي المقام بجوار متوسطة الرڨ الحاج ",
  },
  {
    id:3,
    name: "Laboratoire d'analyse médical El Wiam",
    phone: "0666591156",
    adress: "El wiam",
    localisation: "https://maps.app.goo.gl/xPLptWTx2xR4MuoVA",
  }
];

const doctors = [
  {
    id: 1,
    searchTerm: "allergologie",
    name: "Dr LABBOUB.Kaddour",
    speciality: "Docteur en médecine allergologie",
    adress: "Cité El Wiam, en face le lycée Djoudi Belkacem",
    phone: "029149292",
    email: "k.laaboub@hotmail.fr",
    moreInfo: `Bilan allergologique,test cutané,EFR`,
    localisation: `https://maps.app.goo.gl/HtSHNatssAsZy5ry5`
  },
  {
    id: 2,
    searchTerm: "Médecine générale",
    name: "Dr. Lokbaichi Tahar",
    speciality: "Médecine générale",
    adress: "Cité 600-200 p13 طريق محطة القطار",
    phone: "0557106449",
    phone2: "0699578450",
    email: "",
    moreInfo: "Echographie",
    localisation: "https://maps.app.goo.gl/wPrf5nMxaV1UGyMb9",
  },
  {
    id: 3,
    searchTerm: "Gynécologie obstétrique",
    name: "Dr. Benadjila Mebarek",
    speciality: "Gynécologie obstétrique",
    adress: "Rue el-gharbia",
    phone: "029101585",
    phone2: "0662511456",
    email: "",
    moreInfo: "Néo.Nat.contraception stérilité, Echographie",
    localisation: "https://maps.app.goo.gl/5ptiRAv28g7tN8aR7",
  },
  {
    id: 4,
    searchTerm: "Chirurgien Urologue",
    name: "Dr. Bahat Sofiane",
    speciality: "Chirurgien Urologue",
    adress: "Cité Ben Sahnoun N 003 El Mekam",
    phone: "0659081408",
    phone2: "0551718223",
    phone3: "020782791",
    email: "Dr.bahat.sofiane.urologuqe@gmail.com",
    moreInfo: `Chirurgie et maladie du Rein des voies Urinaires,
     Endoscopie (Prostate, Vessie et calculs), Stérilité Masculine et impuissance, Circoncision`,
    localisation: "https://maps.app.goo.gl/beKBZEj5nyaxDBzW8",
  },
  {
    id: 5,
    searchTerm: "Gynécologie obstétrique",
    name: "Dr. Zagmiri.A",
    speciality: "Médecin Spécialiste en Gynécologie Obstétrique",
    adress: "Cité 127 Logs Bloc 4P N 109 El Ouaimn LSP",
    phone: "0697805001",
    email: "",
    moreInfo: `Suivi de grossesse, échographie 3D/4D, 
    maladie des seins, Frottis, Colposcopie, hystéroscopie 
    diagnostic et opératoire, ERCF, Stérilité du couple, Césarienne, Chirurgie Gynécologique`,
    localisation: "https://maps.app.goo.gl/wxvA3bsU12SU2Ffh9",
  },
  {
    id: 6,
    searchTerm: "Médecine générale",
    name: "Dr. Sadeki Lakhdar",
    speciality: "Médecin Généraliste",
    adress: "",
    phone: "0675865070",
    email: "",
    moreInfo: "",
  },
  {
    id: 7,
    searchTerm: "Diabétologie Endocrinologie",
    name: "Dr. Nasri AbdelHamid",
    speciality:
      "Spécialiste en Diabétologie – Endocrinologie et maladies métaboliques",
    adress: "58 Bis, Rue Amar Telidji, Cité Gharbia (Rue de la poste)",
    phone: "092101003",
    email: "drnasriah@yahoo.fr",
    moreInfo: "",
    localisation: "https://maps.app.goo.gl/AsnzmyzkdqJitvX39"
  },
  {
    id: 8,
    searchTerm: "Gynécologie",
    name: "Dr. Rayane Mohammed",
    speciality: "Gynécologie",
    adress: "Cité Bouameur Maamourah",
    phone: "029131454",
    email: "",
    moreInfo: "Accouchements, Stérilité, Maladies du sein, Echographie",
    localisation: "https://maps.app.goo.gl/LaZsTJDKvxmPiAaR6",
  },
  {
    id: 9,
    searchTerm: "Diabétologie Endocrinologie",
    name: "Dr. El NAGA Kamel",
    speciality: "Endocrinologue Diabétologue",
    adress:
      "Cité Rezzoug Maamourah en face la Gendarmerie au dessus pharmacie Zerrouki",
    phone: "0659828881",
    email: "",
    moreInfo: "",
  },
  {
    id: 10,
    searchTerm: "Médecine générale",
    name: "Dr. Rezig A. Née Benalia",
    speciality: "Médecine Générale",
    adress: "Cité el Wiam En face Bt. Sahraoui",
    phone: "0665973824",
    email: "",
    moreInfo: "Echographie, ECG",
    localisation: "https://maps.app.goo.gl/spTuu7NTi9boWZ3T6",
  },
  {
    id: 11,
    searchTerm: "Médecine interne",
    name: "Dr. Selt Thameur",
    speciality: "Médecine interne",
    adress: "El Wiam وراء محكمة الوئام",
    phone: "0553807666",
    phone2: "029149274",
    email: "",
    moreInfo: `Maladies du cœur et des vaisseaux, Diabète, HTA, 
      le goitre, gastrologie, ECG, échographie, échocardiographie, MAPA, Holter ECG, épreuve d’effort`,
  },
  {
    id: 12,
    searchTerm: "Médecine générale",
    name: "Dr. Adi Boubakeur",
    speciality: "Médecine Générale",
    adress: "Ksar Bezaim Laghouat",
    phone: "0779337630",
    email: "",
    moreInfo: "ECG",
  },
  {
    id: 13,
    searchTerm: "Médecine générale",
    name: "Dr. Chettikh Malika",
    speciality: "Médecine Générale",
    adress: "Cité EL-Gharbia",
    phone: "0778219869",
    email: "",
    moreInfo: "Echographie Gynécologique et obstétricale",
  },
  {
    id: 14,
    searchTerm: "Ophtalmologie",
    name: "Dr. Taibaoui Souleyman",
    speciality: "Maladies & chirurgie des yeux",
    adress: "مجمع حمدي الطبي بالقرب من صيدلية بن شرشافة الوئام",
    phone: "0542035581",
    phone2: "0664806684",
    email: "Dr.taibaoui.s@gmail.com",
    moreInfo: "",
    localisation: "https://maps.app.goo.gl/BX5GNiQri146xmex8",
  },
  {
    id: 15,
    searchTerm: "Médecine générale",
    name: "Dr. Boufateh Othmane Sami",
    speciality: "Docteur en médecine générale",
    adress: "حي برج السنوسي",
    phone: "0662396979",
    phone2: "0540284249",
    email: "",
    moreInfo: "",
  },
  {
    id: 16,
    searchTerm: "Médecine interne",
    name: "Dr. Benzana.z",
    speciality: "Médecin spécialiste",
    adress: "Cité Wiame en face lycée Djoudi Belkacem",
    phone: "0654617382",
    phone2: " 028732535",
    email: "Dr.zigham84@gmail.com",
    moreInfo: `Echographie cardiaque, ECG, MAPA,
     Echographie de thyroïde, Echo-Doppler TSA, 
     Doppler vasculaire artériel et veineux des membres inférieurs et supérieurs`,
  },
  {
    id: 17,
    searchTerm: "Chirurgie Orthopédique",
    name: "Dr. Chettih Aissa",
    speciality: "Spécialiste en Orthopédie - Traumatologie",
    adress: "Laghouat",
    phone: "0770447505",
    email: "",
    moreInfo: "Déclaration d’Accidents de travail et maladies professionnels",
    localisation: "https://maps.app.goo.gl/1LtBMiBVRA8VSqXNA",
  },
  {
    id: 18,
    searchTerm: "Gastro-entérologie",
    name: "Dr. Nazef Nassim",
    speciality: "Spécialiste en Hépato – Gastro – Entérologie",
    adress: "حي الوئام قرب مركز التشخيص الطبي سيفون",
    phone: "0542094198",
    phone2: "0557370365",
    email: "",
    moreInfo: "Proctologie Endoscopie digestive",
    localisation: "https://maps.app.goo.gl/35UyaDRRBbKxHCEL7",
  },
  {
    id: 19,
    searchTerm: "Gynécologie obstétrique",
    name: "Dr. Kherarba.I",
    speciality: "Médecin spécialiste en maladies des femmes et obstétrique",
    adress: "شارع الدكتور سعدان – مقابل مستشفى الأمومة والطفولة-",
    phone: "0697892222",
    email: "",
    moreInfo: `Echographie trois et quatre dimensions,
     infertilité du couple, chirurgie des maladies des 
     femmes et césariennes, maladies et chirurgie du sein`,
  },
  {
    id: 20,
    searchTerm: "Médecine générale",
    name: "Dr. Benkemchi.A",
    speciality: "Médecine Générale",
    adress: "Kheneg Laghouat",
    phone: "029148020",
    email: "",
    moreInfo: "Consultation et soins, Echographie",
  },
  {
    id: 21,
    searchTerm: "Chirurgie Orthopédique",
    name: "Dr. kada djamel",
    speciality: "Chirurgie Orthopédique",
    adress: "Marche Couvert Quartier El Gharbia",
    phone: "029101630",
    localisation: "https://maps.app.goo.gl/Xc3kiJCiAsqGkMhn9",
  },
  {
    id: 22,
    searchTerm: "Neurochirurgue",
    name: "Dr. Koul Ahmed",
    speciality: "Neurochirurgue",
    adress: "AVENUE DU 1 ER NOVEMBRE 1954",
    phone: "0664281077",
  },
  {
    id: 23,
    searchTerm: "Gynécologie obstétrique",
    name: "Dr. Taleb Mehiri Naima",
    speciality: "Gynécologie",
    adress: "El Gharbia",
    phone: "029101641",
    phone2: "0662591241",
    moreInfo: "Accouchement, stérilité, Echographie",
    localisation: "https://maps.app.goo.gl/B6MdPXtd4UTFgab36",
  },
  {
    id: 24,
    searchTerm: "Dermatologie",
    name: "Dr Touti.A",
    speciality: "Dermatologie et vénérologie",
    adress: "El Wiam batiment IRIS",
    phone: "0658213436",
    phone2: "0556020164",
    localisation: "https://maps.app.goo.gl/oKwtp8ZzneDS8R4K8",
  },
  {
    id: 25,
    searchTerm: "Ophtalmologie",
    name: "Dr Takhi.A",
    speciality: "Maladies et chirurgie des yeux",
    adress: "الوئام طريق عدل قرب الحي الجامعي لذكور 2000 سرير ",
    phone: "0675488763",
    moreInfo: "Maladies et Chirurgie des yeux",
  },
  {
    id: 26,
    searchTerm: "Médecine Générale",
    name: "Dr Belboul Afaf eps Belaid",
    speciality: "Médecine Générale",
    adress: "388, cité la douane (près de la pharmacie Belboul)",
    phone: "028736014",
    email: "",
    moreInfo: "",
  },
  {
    id: 27,
    searchTerm: "Chirurgie Orthopédique",
    name: "Dr Benguesmia Mohammed",
    speciality: "Orthopédie Traumatologie",
    adress: "حي الوئام وراء المحمكة",
    phone: "0659165914",
    phone2: "0557382406",
    email: "",
    moreInfo: "طب و جراحة العظام والمفاصل",
  },
  {
    id: 28,
    searchTerm: "Ophtalmologie",
    name: "Dr Kada Rachid",
    speciality: "Maladies et chirurgie des yeux",
    adress: "El Gharbia Bab Errabt",
    phone: "029901490",
    email: "medikada@yahoo.ca",
    moreInfo: "العيادة مغلقة أيام الأربعاء والخميس",
    localisation: "https://maps.app.goo.gl/iQ1XJh62Cngrgmeu5",
  },
  {
    id: 29,
    searchTerm: "Médecine Générale",
    name: "Dr Benaicha Ishak",
    speciality: "Médecine Générale",
    adress: "Cité Oasis Nord",
    phone: "020793735",
    email: "",
    moreInfo: "Médecin urgentiste",
  },
  {
    id: 30,
    searchTerm: "Cardiologie",
    name: "Dr Ghorab M.A",
    speciality: "Cardiologie adulte et pédiatrique",
    adress: "Cité Wiame Laghouat",
    phone: "0553807666",
    email: "GHORABAMINE83@gmail.com",
    moreInfo: `ECG – Holter ECG – MAPA  
      Echocardiographie doppler  
      Epreuve d’effort`,
  },
  {
    id: 31,
    searchTerm: "Gynécologie Obstétrique",
    name: "Dr Guenou Khadidja",
    speciality: "Spécialiste en gynécologie obstétrique",
    adress: "Rue Elhorma Ahmed M’kam Laghouat",
    phone: "0558406997",
    phone2: "0655421429",
    email: "",
    moreInfo: "Stérilité – Échographie Doppler – ERCF – Colposcopie",
    localisation: "https://maps.app.goo.gl/hdWXzmeF7FQYcz5bA",
  },
  {
    id: 32,
    searchTerm: "Médecine Générale",
    name: "Dr Hamdi Amina",
    speciality: "Médecine Générale",
    adress: "Cité Esaada Oasis Nord",
    phone: "0559853067",
    email: "",
    moreInfo: "Échographie 3D-4D – Suivi de grossesse",
    localisation: "https://maps.app.goo.gl/HJJsCudVs5rEQpQW8",
  },
  {
    id: 33,
    searchTerm: "Gynécologie Obstétrique",
    name: "Dr Souiah A",
    speciality: "Spécialiste en gynécologie obstétrique",
    adress: "El Gharbia",
    phone: "0664158338",
    email: "",
    moreInfo: `Suivi de grossesse normale et à risque  
      Échographie pelvienne et obstétricale  
      Stérilité du couple, maladie des seins  
      Accouchement normal et césarienne`,
  },
  {
    id: 34,
    searchTerm: "Néphrologie",
    name: "Dr Nait Elhocine A",
    speciality: "Spécialiste en néphrologie",
    adress: "Cité 252 Logements groupement 152 Maamourah",
    phone: "029102260",
    phone2: "0772448978",
    email: "",
    moreInfo: "",
    localisation: "https://g.co/kgs/SqoN1ta",
  },
  {
    id: 35,
    searchTerm: "Médecine Générale",
    name: "Dr Benarous Nadjia",
    speciality: "Médecine Générale",
    adress: "Schettet El-Gharbi",
    phone: "0673306414",
    email: "",
    moreInfo: "",
  },
  {
    id: 36,
    searchTerm: "Dentist",
    name: "Dr Oulmehdi.w Épse Bouchria ",
    speciality: "Cabinet Dentaire",
    adress: "Cité el-wiam en face des bâtiments SAHRAOUI",
    phone: "0656769557",
    moreInfo:
      "Soins dentaires, extractions, soin des gencives et détartrage, blanchiment",
    localisation: "https://maps.app.goo.gl/2sHZYDthRPgsEG6E6",
  },
  {
    id: 37,
    seachTerm: "Dentist",
    name: "Dr Idriss Belbali",
    speciality: "Dentist, Orthodontist",
    adress: "Cité Maamoura Bouameur, en Face du grand Bazar",
    phone: "0662279191",
    localisation: "https://maps.app.goo.gl/ucbpJfNi1ZTmE6f1A",
  },
  {
    id: 38,
    searchTerm: "Dentist",
    name: "Dr Bentaieb Bohamed",
    speciality: "Dentist",
    adress: "n 8. Bat E. Cite 128 LSP m'hafir (mostakbel)",
    phone: "028732323",
    localisation: "https://maps.app.goo.gl/1P7jc9bbvUNHA3mL9",
  },
  {
    id: 39,
    searchTerm: "Dentist",
    name: "Dr Belboul Mohamed Amine",
    speciality: "Dentist",
    adress: "rue maamoura près des grossistes",
    phone: "0658509848",
    localisation: "https://maps.app.goo.gl/UE6qFJv1n39QRqL79",
  },
  {
    id: 40,
    searchTerm: "MédecineGénérale ",
    name: "Dr CHETTIH.F née Mansouri",
    speciality: "Médecine Générale",
    adress: "Schettet elgharbi	",
    phone: "029118250",
  },
  {
    id: 41,
    searchTerm: "Chirurgien Urologue",
    name: "Dr Korichi Thameur",
    speciality: "Chirurgien urologue",
    adress: "Aflou",
    phone: "0770269948",
  },
  {
    id: 42,
    searchTerm: "Hématologue",
    name: "Dr Saidani.K",
    speciality: "Hématologue",
    adress: "رقم 140, حي المصالحة 240 مسكن تساهمي",
    phone: "0551580206",
  },
  {
    id: 43,
    searchTerm: "Neurologie",
    name: "DR Dameche Rachida",
    speciality: "Spécialist en neurologie",
    adress: "Av docteur saadane",
    phone: "029134960",
    phone2: "0775103192",
    moreinfro: "EMG, EEG, PE",
    localisation: "https://maps.app.goo.gl/Vt1Wk4JhEQesgtSk6",
  },
  {
    id: 44,
    searchTerm: "Médecine Générale",
    name: "Dr Grine Med Lamine",
    speciality: "Médecine Générale",
    adress: "Cité Bouameur maamoura",
    phone: "0770570038",
    localisation: "https://maps.app.goo.gl/tEssqmW7cDALYewt7",
  },
  {
    id: 45,
    searchTerm: "Médecine Générale",
    name: "Dr Mouhouch Said",
    speciality: "Médecine Générale",
    adress: "Bellil – Hassi R’mel",
    phone: "0699265665",
  },
  {
    id: 46,
    searchTerm: "Anesthésie Réanimation",
    name: "Dr Touhami.B",
    speciality: "Spécialiste en Anesthésie Réanimation",
    adress: "Rue ElKhansaa El Gharbia",
    phone: "0773264279",
    moreInfo: "Examen pré-anesthésique, HTA, Diabète",
  },
  {
    id: 47,
    searchTerm: "Rhumatologie",
    name: "Dr Boulaghmen / Benrahal.B",
    speciality: "Médecin rhumatologue",
    adress: "El Gharbia",
    phone: "0663221438",
    moreInfo:
      "Infiltration intra-articulaire et intradurale\nمختصة في أمراض العظام والروماتيزم",
  },
  {
    id: 48,
    searchTerm: "Diabétologie Endocrinologie",
    name: "Dr Khoukhi.A",
    speciality: "Endocrinologie",
    adress: "Cité 800 logements à côté de lycée Mimouni AEK",
    phone: "0697998287",
    phone2: "029125826",
    moreInfo: "أمراض السكري والغدد الصماء",
    localisation: "https://maps.app.goo.gl/e3rViLcWCRUwfkfp6",
  },
  {
    id: 49,
    searchTerm: "Néphrologie",
    name: "Dr Khoukhi Karim",
    speciality: "Néphrologie",
    adress: "Cité 800 logements à côté de lycée Mimouni AEK",
    phone: "0697998287",
    phone2: "029125826",
    moreInfo: "أخصائي أمراض الكلى والجهاز البولي",
    localisation: "https://maps.app.goo.gl/e3rViLcWCRUwfkfp6",
  },
  {
    id: 50,
    searchTerm: "Dermatologie",
    name: "Dr Hassani Mohamed",
    speciality: "Dermatologue Vénérologue",
    adress: "50 Bis, Rue Amar Telidji, cité Gharbia (rue de la poste)",
    phone: "029101708",
    moreInfo: `Maladies de peau, ongles, cuir chevelu\nChirurgie Dermatologique – 
    Cryothérapie\nEpilation – ionophorèse – lasers`,
    localisation: "https://maps.app.goo.gl/t7gUerw32M2b7aEe8",
  },
  {
    id: 51,
    searchTerm: "Pédiatrie",
    name: "Dr Chehami Ahmed",
    speciality: "Pédiatre",
    adress: "Hai El Gharbia",
    phone: "029101735",
    email: "Chehami@hotmail.com",
  },
  {
    id: 52,
    searchTerm: "Médecine Générale",
    name: "Dr Aissat Ahmed",
    speciality: "Médecine Généraliste",
    adress: "حي قسمية بن حرزالله / قصر الحيران",
    phone: "0673001046",
    phone2: "029139302",
  },
  {
    id: 53,
    searchTerm: "Chirurgie Générale",
    name: "Dr Hamek Azzeddine",
    speciality: "Spécialiste en Chirurgie Générale et Coelioscopique",
    adress: "شارع الأمير عبدالقادر حي 80 سكن عمارة رقم 7 افلو",
    phone: "0552912659",
    localisation: "https://maps.app.goo.gl/WqHXfaiUegovGoPi7",
  },
  {
    id: 54,
    searchTerm: "Echographie",
    name: "Dr Benothmane Djamal",
    speciality: "Médecine Générale",
    adress: "Rue Dr Saadane",
    phone: "029134962",
    moreInfo:
      "Echographie abdominale, gynéco-obstétricale, thyroïde, sein\nMAPA, ECG, IPS",
  },
  {
    id: 55,
    searchTerm: "Chirurgie Générale",
    name: "Dr Selmane Youcef",
    speciality: "Spécialiste en Chirurgie Générale",
    adress: "شارع فرانس فانون أفلو",
    phone: "029161795",
    phone2: "0699438266",
    moreInfo: "Chirurgie Viscérale et Coelio – Chirurgie",
  },
  {
    id: 56,
    searchTerm: "Médecine Générale",
    name: "Dr Rezgallah.Y",
    speciality: "Médecine Générale",
    adress: "Cité El M’Kam Maamourah",
    phone: "029116501",
    phone2: "0696986655",
    moreInfo: "Échographie – Mésothérapie",
  },
  {
    id: 57,
    searchTerm: "Médecine Générale",
    name: "Dr Houamdi Youcef",
    speciality: "Médecin Généraliste",
    adress: "Cité M’kam en face lycée Hadj Aissa",
    phone: "0655547285",
  },
  {
    id: 58,
    searchTerm: "Médecine Générale",
    name: "Dr Daoudi Ahmida",
    speciality: "Médecine Générale",
    adress: "Rue de l'independance",
    phone: "0669289906",
    moreInfo: "Méothérapie",
    localisation: "https://maps.app.goo.gl/MKyEd3ux3TgmF44W9",
  },
  {
    id: 59,
    searchTerm: "Gastro-entérologie",
    name: "Dr Tadj Djelloul Amine",
    speciality: "Médecin spécialiste en Hépto-Gastro-Entérologie",
    adress: "شارع المقام",
    phone: "0698200030",
    email: "Tadj-gastroclinic@gmail.com",
    moreInfo: "Entérologie – Proctologie – Endoscopie digestive",
    localisation: "https://maps.app.goo.gl/i1YkudeiofccP5Gg7",
  },
  {
    id: 60,
    searcTerm: "Pédiatrie",
    name: "Dr A.Faïd épse. Ghorab",
    speciality: "Pédiatre",
    adress: "وراء محكمة الوئام مقابل مسجد عبدالله بن عمر",
    phone: "0699067724",
    localisation: "https://maps.app.goo.gl/uRdTH15SgGyi5wHs7",
  },
  {
    id:61,
    searchTerm:"Médecine Générale",
    name: "Dr Reggab Ameur",
    speciality: "médecine Générale",
    adress: "حي 240 سكن تساهمي الوئام",
    phone: "0657111880",
    moreInfo: "Echographie urgence",
  },
  {
    id:62,
    searchTerm: "Médecine Générale",
    name: "Dr Kaci slimane",
    speciality: "Medcine généraliste, Néonpatologie",
    adress: "rue mechouar benaissa aflou",
    phone: "0771991307"
  },
  {
    id:63,
    searchTerm: "Médecine Générale",
    name: "Dr Choucha Noureddine",
    speciality: "Médecine Générale",
    adress: "ksar el hirane",
    phone: "029139595",
    phone2: "0799099991",
    moreInfo: "Echographie generale, ECG, MAPA",
    localisation: "https://maps.app.goo.gl/okmtRV2M5kt4jdaX6",
  },
  {
    id: 64,
    searchTerm: "Neurologie",
    name: "Dr Boulahbel.H",
    speciality: "Neurologue",
    adress: "en face de la daïra de, Av. de l’Indépendance",
    phone: "0556808520",
    phone2: "029101834",
    moreInfo: "EEG, ENMG",
    localisation: "https://maps.app.goo.gl/NTxAHiGA9V1NxR7r8",
  },
  {
    id:65,
    searchTerm: "Chirurgie Générale",
    name: "Dr Ferhat Bachir",
    speciality: "Chirurgien",
    adress: "Cité Bouameur Maamourah",
    phone: "029131884",
    localisation: "https://maps.app.goo.gl/yXdxnLg4X1C9LyVWA",
  },
  {
    id:66,
    searchTerm: "Médecine Générale",
    name: "Dr Maicha A/hamid",
    speciality: "Médecine Générale",
    adress: "cité wiam",
    phone: "029128404",
    phone2: "0667821800",
    moreInfo: "diiabétologie Ecographie",
    localisation: "https://maps.app.goo.gl/CPQNxVbRgQdC6m1T6",
  },
  {
    id: 67,
    searchTerm: "Chirurgie Orthopédique",
    name: "Dr Choucha Belkacem",
    speciality: `Spécialiste Orthopédie traumatologie
      & arthroscopie`,
    adress: "",
    phone: "0670666060",
    email: "cabinetchoucha25@gmail.com",
  },
  {
    id: 68,
    searchTerm: "Pédiatrie",
    name: "Dr Bouzara Aissa",
    speciality: "spécialiste en pediatrie et néonatalogie",
    adress: "Rue Bachir Rezzoug",
    phone: "06994255201",
    email: "bouzara03@gmail.com",
    localisation: "https://maps.app.goo.gl/5X3U5Lp3Aeht7VyE9",
  },
  {
    id: 69,
    searchTerm: "ORL",
    name: "Dr Kadi S.N",
    speciality: "Médecin spécialiste ORL",
    adress: "Cité Wiam en face lycée Djoudi Belkacem",
    phone:"0560653982",
    phone2:"029149109",
    moreInfo: `Maladies et chirurgie Nez, Gorge, Oreille, thyroide
      Chirurgie endoscopique nasofibroscopie
      otoendoscopie, audiométrie, allergologie`, 
    localisation: "https://maps.app.goo.gl/BkPKqhdvwCMaiXTBA",
  },
  {
    id: 70,
    searchTerm: "Médecine générale",
    name: "Daoudi . A",
    speciality: "Médecin General et Mésotherapie",
    adress: "عين ماضي",
    phone:"0793160747",
    moreInfo: `طب رجال ونساء واطفال وأمراض الجلد`, 
  },
  {
    id: 71,
    searcTerm: "Cardiologie",
    name: "Remmach Djelloul",
    speciality: "Médecin spécialist Cardiologue",
    adress: "El-Gharbia",
    phone: "0665906314",
    phone1: "029101736",
    moreInfo: `Maladies Cardiovasculaires, Electrocardiographie
      Echocardiographie-Dopler, Mesure Ambulatoire de la pression Arterielle(MAPA)`,
    localisation: 'https://maps.app.goo.gl/Vk2qSrk1jacTrfY78',
  },
  {
    id:72,
    searcTerm: "Dermatologie",
    name: "الدكتورة فرنان. ي حرم اوكيد",
    speciality: "Dermatologie et vénérologie",
    adress: "حي الوئام وراء المحكمة",
    phone: "0665791606",
    localisation: "https://maps.app.goo.gl/CZcmDLfa75c9ERWi7",
  },
  {
    id: 73,
    searchTerm: "Médecine générale",
    name: "الحكيم حشاني حشاني",
    speciality: "Médecine générale",
    adress: "Maamourah cité  482 Bloc 47 N2",
    phone: "029100336",
    phone1: "0663211613",
    localisation: "https://maps.app.goo.gl/z6WDin1hscp2drDTA",
  }
];

const imagingCenters = [
  {
    id: 1,
    name: "Le Centre d’Imagerie Médicale ESPOIR",
    director: "Dr. M. Laghouati",
    adress: "Rue BENSAHNOUN lmkam",
    phone: "0541922720",
    phone2: "0770389410",
    phone3: "020782877",
    email: "cim.espoir@gmail.com",
    workTime: "8:00-00h00",
    localisation: "https://maps.app.goo.gl/TcoNBSAjRMfGPBqJ7",
  },
  {
    id: 2,
    name: "Centre D'Imagerie Médicale Chifa Dr BENOMAR",
    director: "Dr. BENOMAR",
    adress: "وراء محكمة الوئام",
    phone: "0671731020",
    email: "chifaradiology@gmail.com",
    localisation: "https://maps.app.goo.gl/UGRnbM4Pg96hLGGP9",
  },
  {
    id: 3,
    name: "Centre d'imagerie médicale Dr Seifoune Farid",
    director: "Dr. Seifoune Farid",
    adress: "Cité El Wiam 591 Logs",
    phone: "029149912",
    phone2: "0771996423",
    email: "farid.seifoune@yahoo.fr",
    moreInfo: `Scanner hélicoïdal 3D – Radiologie générale – Mammographie\n
      Échographie générale – Echodoppler couleur – Ostéodensitométrie (D.M.O)\n
      Panoramique dentaire – Radiologie interventionnelle`,
    localisation: "https://maps.app.goo.gl/Q7fDCTuganzk4hx16",
  },
];

export { labs, doctors, imagingCenters };
